"""Markdown and HTML report generation from audit results."""

from models.audit_finding import AUDIT_GROUPS
from models.audit_result import AuditResult
from utils.formatting import severity_badge_md, format_number


def generate_markdown_report(result: AuditResult) -> str:
    """Generate a complete Markdown audit report."""
    lines: list[str] = []

    # Header
    lines.append(f"# GSC Audit Report — {result.property_url}")
    lines.append("")
    lines.append(f"**Audit Date:** {result.audit_timestamp[:10]}")
    lines.append(f"**Analysis Period:** {result.start_date} to {result.end_date}")
    lines.append(f"**Tasks Executed:** {len(result.tasks_executed)}")
    lines.append(f"**Total Findings:** {result.total_findings}")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Executive Summary
    if result.ai_executive_summary:
        lines.append("## Executive Summary")
        lines.append("")
        lines.append(result.ai_executive_summary)
        lines.append("")
        lines.append("---")
        lines.append("")

    # Health Score
    lines.append("## Health Score")
    lines.append("")
    lines.append(f"**Score:** {result.health_score}/100 | **Grade:** {result.health_grade}")
    lines.append("")
    lines.append("### Findings by Severity")
    lines.append("")
    for sev, count in result.severity_counts.items():
        lines.append(f"- {severity_badge_md(sev)}: {count}")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Group-by-Group Findings
    for group_id in sorted(result.findings_by_group.keys()):
        group_findings = result.findings_by_group[group_id]
        group_name = AUDIT_GROUPS.get(group_id, f"Group {group_id}")

        lines.append(f"## Group {group_id}: {group_name}")
        lines.append("")
        lines.append(f"*{len(group_findings)} findings*")
        lines.append("")

        for finding in sorted(group_findings, key=lambda f: f.severity.priority):
            lines.append(
                f"### {severity_badge_md(finding.severity.value)} Task {finding.task_id}: {finding.task_name}"
            )
            lines.append("")
            lines.append(finding.summary)
            lines.append("")

            if finding.affected_count > 0:
                lines.append(f"**Affected Items:** {format_number(finding.affected_count)}")

            if finding.opportunity_value:
                lines.append(f"**Opportunity:** {finding.opportunity_value}")

            if finding.recommendations:
                lines.append("")
                lines.append("**Recommendations:**")
                for rec in finding.recommendations:
                    lines.append(f"- {rec}")

            if finding.data_table is not None and not finding.data_table.empty:
                lines.append("")
                lines.append("**Data:**")
                lines.append("")
                lines.append(finding.data_table.head(20).to_markdown(index=False))

            lines.append("")
            lines.append("---")
            lines.append("")

        # AI Group Analysis
        if group_id in result.ai_group_analyses:
            lines.append(f"### AI Analysis — {group_name}")
            lines.append("")
            lines.append(result.ai_group_analyses[group_id])
            lines.append("")
            lines.append("---")
            lines.append("")

    # Content Optimization Plan
    if result.ai_content_plan:
        lines.append(result.ai_content_plan)
        lines.append("")
        lines.append("---")
        lines.append("")

    # Footer
    lines.append("---")
    lines.append(f"*Report generated by GSC Audit Agent on {result.audit_timestamp[:10]}*")

    return "\n".join(lines)


def generate_html_report(result: AuditResult) -> str:
    """Generate a styled HTML audit report."""
    md_content = generate_markdown_report(result)

    severity_colors = {
        "CRITICAL": "#DC2626",
        "HIGH": "#EA580C",
        "MEDIUM": "#CA8A04",
        "LOW": "#2563EB",
        "INSIGHT": "#6B7280",
    }

    html_parts: list[str] = []
    html_parts.append(f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>GSC Audit Report — {result.property_url}</title>
<style>
    * {{ margin: 0; padding: 0; box-sizing: border-box; }}
    body {{
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
        line-height: 1.6;
        color: #1a1a2e;
        background: #f8f9fa;
        padding: 2rem;
        max-width: 1200px;
        margin: 0 auto;
    }}
    h1 {{ font-size: 1.8rem; margin-bottom: 0.5rem; color: #1a1a2e; }}
    h2 {{
        font-size: 1.4rem;
        margin-top: 2rem;
        margin-bottom: 1rem;
        padding-bottom: 0.5rem;
        border-bottom: 2px solid #e2e8f0;
        color: #2d3748;
    }}
    h3 {{ font-size: 1.1rem; margin-top: 1.5rem; margin-bottom: 0.5rem; color: #4a5568; }}
    p {{ margin-bottom: 0.8rem; }}
    ul {{ margin-left: 1.5rem; margin-bottom: 1rem; }}
    li {{ margin-bottom: 0.3rem; }}
    hr {{ border: none; border-top: 1px solid #e2e8f0; margin: 1.5rem 0; }}
    table {{
        border-collapse: collapse;
        width: 100%;
        margin: 1rem 0;
        font-size: 0.85rem;
    }}
    th, td {{
        border: 1px solid #e2e8f0;
        padding: 0.5rem 0.75rem;
        text-align: left;
    }}
    th {{ background: #f7fafc; font-weight: 600; color: #4a5568; }}
    tr:nth-child(even) {{ background: #f7fafc; }}
    .header-meta {{ color: #718096; font-size: 0.9rem; margin-bottom: 0.3rem; }}
    .health-score {{
        display: inline-block;
        padding: 0.5rem 1.5rem;
        border-radius: 8px;
        font-size: 1.5rem;
        font-weight: 700;
        color: white;
        margin: 1rem 0;
    }}
    .grade-A {{ background: #38A169; }}
    .grade-B {{ background: #68D391; color: #1a1a2e; }}
    .grade-C {{ background: #ECC94B; color: #1a1a2e; }}
    .grade-D {{ background: #ED8936; }}
    .grade-F {{ background: #E53E3E; }}
    .severity-badge {{
        display: inline-block;
        padding: 0.15rem 0.5rem;
        border-radius: 4px;
        font-size: 0.75rem;
        font-weight: 600;
        color: white;
    }}
    .group-section {{
        background: white;
        border-radius: 8px;
        padding: 1.5rem;
        margin-bottom: 1.5rem;
        box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }}
    .finding {{
        border-left: 3px solid #e2e8f0;
        padding-left: 1rem;
        margin-bottom: 1.5rem;
    }}
    .finding-critical {{ border-left-color: #DC2626; }}
    .finding-high {{ border-left-color: #EA580C; }}
    .finding-medium {{ border-left-color: #CA8A04; }}
    .finding-low {{ border-left-color: #2563EB; }}
    .finding-insight {{ border-left-color: #6B7280; }}
    details {{ margin-bottom: 1rem; }}
    summary {{
        cursor: pointer;
        font-weight: 600;
        padding: 0.5rem;
        background: #f7fafc;
        border-radius: 4px;
    }}
    summary:hover {{ background: #edf2f7; }}
    @media print {{
        body {{ padding: 1rem; background: white; }}
        .group-section {{ box-shadow: none; border: 1px solid #e2e8f0; }}
        details[open] summary {{ background: white; }}
    }}
</style>
</head>
<body>

<h1>GSC Audit Report</h1>
<p class="header-meta">{result.property_url}</p>
<p class="header-meta">Audit Date: {result.audit_timestamp[:10]} | Period: {result.start_date} to {result.end_date}</p>
<p class="header-meta">Tasks Executed: {len(result.tasks_executed)} | Total Findings: {result.total_findings}</p>

<div class="health-score grade-{result.health_grade}">
    {result.health_score}/100 — Grade {result.health_grade}
</div>
""")

    # Severity summary
    html_parts.append('<div style="display:flex;gap:1rem;margin:1rem 0;flex-wrap:wrap;">')
    for sev, count in result.severity_counts.items():
        color = severity_colors.get(sev.upper(), "#6B7280")
        html_parts.append(
            f'<div style="text-align:center;">'
            f'<span class="severity-badge" style="background:{color};">{sev.upper()}</span>'
            f'<div style="font-size:1.5rem;font-weight:700;margin-top:0.3rem;">{count}</div>'
            f'</div>'
        )
    html_parts.append('</div><hr>')

    # Executive Summary
    if result.ai_executive_summary:
        html_parts.append('<div class="group-section">')
        html_parts.append('<h2>Executive Summary</h2>')
        for para in result.ai_executive_summary.split("\n\n"):
            para = para.strip()
            if para:
                if para.startswith("#"):
                    level = para.count("#", 0, 4)
                    text = para.lstrip("#").strip()
                    html_parts.append(f"<h{level+1}>{text}</h{level+1}>")
                elif para.startswith("- "):
                    html_parts.append("<ul>")
                    for item in para.split("\n"):
                        item = item.lstrip("- ").strip()
                        if item:
                            html_parts.append(f"<li>{item}</li>")
                    html_parts.append("</ul>")
                else:
                    html_parts.append(f"<p>{para}</p>")
        html_parts.append('</div>')

    # Group findings
    for group_id in sorted(result.findings_by_group.keys()):
        group_findings = result.findings_by_group[group_id]
        group_name = AUDIT_GROUPS.get(group_id, f"Group {group_id}")

        html_parts.append('<div class="group-section">')
        html_parts.append(f'<h2>Group {group_id}: {group_name}</h2>')
        html_parts.append(f'<p><em>{len(group_findings)} findings</em></p>')

        for finding in sorted(group_findings, key=lambda f: f.severity.priority):
            sev = finding.severity.value
            color = severity_colors.get(sev.upper(), "#6B7280")
            html_parts.append(f'<div class="finding finding-{sev}">')
            html_parts.append(
                f'<h3><span class="severity-badge" style="background:{color};">'
                f'{sev.upper()}</span> Task {finding.task_id}: {finding.task_name}</h3>'
            )
            html_parts.append(f'<p>{finding.summary}</p>')

            if finding.affected_count > 0:
                html_parts.append(f'<p><strong>Affected Items:</strong> {format_number(finding.affected_count)}</p>')
            if finding.opportunity_value:
                html_parts.append(f'<p><strong>Opportunity:</strong> {finding.opportunity_value}</p>')

            if finding.recommendations:
                html_parts.append('<p><strong>Recommendations:</strong></p><ul>')
                for rec in finding.recommendations:
                    html_parts.append(f'<li>{rec}</li>')
                html_parts.append('</ul>')

            if finding.data_table is not None and not finding.data_table.empty:
                html_parts.append('<details><summary>View Data</summary>')
                html_parts.append(finding.data_table.head(20).to_html(index=False, classes='data-table'))
                html_parts.append('</details>')

            html_parts.append('</div>')

        # AI group analysis
        if group_id in result.ai_group_analyses:
            html_parts.append('<details><summary>AI Analysis</summary>')
            for para in result.ai_group_analyses[group_id].split("\n\n"):
                para = para.strip()
                if para:
                    html_parts.append(f"<p>{para}</p>")
            html_parts.append('</details>')

        html_parts.append('</div>')

    # Content Plan
    if result.ai_content_plan:
        html_parts.append('<div class="group-section">')
        html_parts.append('<h2>Content Optimization Plan</h2>')
        for para in result.ai_content_plan.split("\n\n"):
            para = para.strip()
            if para:
                if para.startswith("#"):
                    level = min(para.count("#", 0, 5), 4)
                    text = para.lstrip("#").strip()
                    html_parts.append(f"<h{level+1}>{text}</h{level+1}>")
                elif para.startswith("- "):
                    html_parts.append("<ul>")
                    for item in para.split("\n"):
                        item = item.lstrip("- ").strip()
                        if item:
                            html_parts.append(f"<li>{item}</li>")
                    html_parts.append("</ul>")
                else:
                    html_parts.append(f"<p>{para}</p>")
        html_parts.append('</div>')

    # Footer
    html_parts.append(f'<p style="color:#718096;text-align:center;margin-top:2rem;">')
    html_parts.append(f'Report generated by GSC Audit Agent on {result.audit_timestamp[:10]}')
    html_parts.append('</p>')
    html_parts.append('</body></html>')

    return "\n".join(html_parts)
